# Generated by Django 4.1.7 on 2023-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Film İsim')),
                ('image', models.ImageField(upload_to='Films', verbose_name='Film Resim')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmler',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Dizi İsim')),
                ('image', models.ImageField(upload_to='Series', verbose_name='Dizi Resim')),
            ],
            options={
                'verbose_name': 'Dizi',
                'verbose_name_plural': 'Diziler',
            },
        ),
    ]
