# Generated by Django 4.1.7 on 2023-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('title', models.CharField(max_length=150, verbose_name='isim')),
                ('image', models.ImageField(max_length=150, upload_to='Content', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'İçerik',
                'verbose_name_plural': 'İçerikler',
            },
        ),
    ]
