# Generated by Django 4.1.7 on 2023-04-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_series_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='user',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
