# Generated by Django 4.1.7 on 2023-04-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_remove_series_user_delete_films_delete_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Tür')),
                ('title', models.CharField(max_length=100, verbose_name='İsim')),
                ('image', models.ImageField(max_length=150, upload_to='Contents', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'İçerik',
                'verbose_name_plural': 'İçerikler',
            },
        ),
    ]
