# Generated by Django 4.1.7 on 2023-04-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0006_contents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
